global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: feed-service
    static_configs:
      - targets: ["feed-service:9101"]
  - job_name: post-service
    static_configs:
      - targets: ["post-service:9100"]
  - job_name: fanout-worker
    static_configs:
      - targets: ["fanout-worker:9102"]
  - job_name: gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["gateway:8080"]
  - job_name: social-graph-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["social-graph-service:8081"]
